FROM rust:1.97.0-bullseye@sha256:a1bcf9c3ecf306817ae1dcf742f3764d475e07fec39aaea7a49ca61a7bb1be1c AS rust-toolchain

FROM ubuntu:22.04@sha256:0d779ea97881505f5ef0039336ee85edba27519bdba968c284c86ee066a973c8

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        binutils \
        build-essential \
        ca-certificates \
        clang \
        cmake \
        curl \
        desktop-file-utils \
        file \
        git \
        libdbus-1-dev \
        libfontconfig1-dev \
        libfuse2 \
        libgtk-3-dev \
        liblzma-dev \
        libssl-dev \
        libwayland-dev \
        libx11-dev \
        libx11-xcb-dev \
        libxcb-render0-dev \
        libxcb-shape0-dev \
        libxcb-xfixes0-dev \
        libxcb1-dev \
        libxkbcommon-dev \
        libxkbcommon-x11-0 \
        lintian \
        patchelf \
        pkg-config \
        rsync \
        shellcheck \
        squashfs-tools \
        xz-utils \
    && rm -rf /var/lib/apt/lists/*

COPY --from=rust-toolchain /usr/local/cargo /usr/local/cargo
COPY --from=rust-toolchain /usr/local/rustup /usr/local/rustup

ENV CARGO_HOME=/usr/local/cargo \
    RUSTUP_HOME=/usr/local/rustup \
    PATH=/usr/local/cargo/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    APPIMAGE_EXTRACT_AND_RUN=1

RUN rustup component add clippy rustfmt \
    && cargo install --locked cargo-deb --version 3.7.0

ARG LINUXDEPLOY_VERSION=1-alpha-20251107-1
ARG LINUXDEPLOY_SHA256=c20cd71e3a4e3b80c3483cef793cda3f4e990aca14014d23c544ca3ce1270b4d
ARG APPIMAGE_PLUGIN_VERSION=1-alpha-20250213-1
ARG APPIMAGE_PLUGIN_SHA256=992d502a248e14ab185448ddf6f6e7d25558cb84d4623c354c3af350c25fccb3

RUN curl --fail --location --silent --show-error \
        --output /usr/local/bin/linuxdeploy \
        "https://github.com/linuxdeploy/linuxdeploy/releases/download/${LINUXDEPLOY_VERSION}/linuxdeploy-x86_64.AppImage" \
    && printf '%s  %s\n' "${LINUXDEPLOY_SHA256}" /usr/local/bin/linuxdeploy | sha256sum --check \
    && curl --fail --location --silent --show-error \
        --output /usr/local/bin/linuxdeploy-plugin-appimage \
        "https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/${APPIMAGE_PLUGIN_VERSION}/linuxdeploy-plugin-appimage-x86_64.AppImage" \
    && printf '%s  %s\n' "${APPIMAGE_PLUGIN_SHA256}" /usr/local/bin/linuxdeploy-plugin-appimage | sha256sum --check \
    && chmod 0755 /usr/local/bin/linuxdeploy /usr/local/bin/linuxdeploy-plugin-appimage

WORKDIR /build/work
